### ISSUE TITLE
Error: Circular dependency: clever-accounts

### ISSUE THREAD

**Issue by stvogel** [CleverStack/clever-orm#34]
I'm trying to install clever-orm with:
```clever install clever-orm```

I get:
    Attempting to install clever-orm...
      ├── Searching for modules...
      ├──   Searching NPM...
      ├──   Searching Bower...
      ├── ⚠ Installing clever-orm...
      ├── Installing NPM modules for clever-orm...
    ✔    Successfully installed clever-orm...
      ├── Installing bundledDependencies...
    /usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:33
          throw new Error('Circular dependency: '+dep);
                ^
    Error: Circular dependency: clever-accounts
        at /usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:33:13
        at Array.forEach (native)
        at DepTree.resolveNode (/usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
        at /usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:35:10
        at Array.forEach (native)
        at DepTree.resolveNode (/usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
        at /usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:35:10
        at Array.forEach (native)
        at DepTree.resolveNode (/usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:28:8)
        at DepTree.resolve (/usr/local/lib/node_modules/cleverstack-cli/node_modules/deptree/index.js:49:10)

Why is clever-orm dependent on clever-accounts?
I really like the idea of cleverstack and am eager to use it in a projectm but the complete lack of any tutorial/documentation is very frustrating,

**Comment by pilsy** [comment]
hi @stvogel, i have fixed the problem.

`npm cache clean`
`clever init myProject`
`cd myProject`
`clever install clever-orm` - follow the prompts (create your database table before doing this)
`clever install clever-users clever-auth`
`cd backend`
`grunt db`

That will get you the latest stack including both the frontend and backend, as well as installing the clever-orm, clever-users, clever-auth, clever-accounts and clever-roles cleverstack modules - you will have seedData defined (data in your tables), `clever serve` and visit http://localhost:9000 and you will see the frontend, http://localhost:8080/auth/session and you will get the backend.

Let me know how you go

**Comment by stvogel** [comment]
Thanks @pilsy for your help.
Installation of clever-orm is doing find now.
But when I execute 4. clever install clever-users clever-auth

  ├── Installing modules: clever-roles
✔      Found CleverStack Backend (node-seed) in /Users/stefanvogel/Documents/projects/angular/cleverstack.io/procbi/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-roles...
  ├── Installing NPM modules for clever-roles...
✔    Successfully installed clever-roles...
  ├── Installing bundledDependencies...
Possibly unhandled TypeError: Object Error: Cannot find module 'config' has no method 'match'
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:73:26

Sorry. Do you know what is wrong here?

**Comment by jollyrogersfabric** [comment]
Got the same problem. Any work around that works for this?

**Comment by pilsy** [comment]
@stvogel @jollyrogersfabric - can you please run the command with the -v or --verbose option and paste the result in this ticket? it's the only way i can know what's really going on

**Comment by stvogel** [comment]
This is what it looks like with -v

clever install -v clever-users clever-auth
Attempting to install clever-auth...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-auth...
  ├── Installing NPM modules for clever-auth...
✔    Successfully installed clever-auth...
  ├── Installing bundledDependencies...
  ├── ⚠ Running grunt tasks for module clever-auth...
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'config'
Warning: Task "prompt:cleverAuthConfig" not found. Use --force to continue.

Aborted due to warnings.
✔  Successfully installed.

I would like to understand something, but I'm not too deep into that. Can you make anything out of that?

**Comment by pilsy** [comment]
Unfortunately that doesn't help a great deal, but all good let's keep debugging :)

Did you run this command with a fresh init?

**Comment by pilsy** [comment]
Here's the result of me installing the latest node-seed, clever-orm, clever-auth, clever-users, clever-accounts and clever-roles...

`
clever init test2-feb-2015 backend -f

Preparing for installation...
  └── Creating project installation path...

Installing Backend...
  ├── Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...
  └── Installing bundledDependencies...
✔  Backend installation has completed successfully!

✔  Project test2-feb-2015 has been created in /Users/richardgustin/Documents/Projects/CleverStack/Workspace/test2-feb-2015

Status @ 24s |   Installation Progress: [▒▒▒▒▒▒▒▒▒▒]  100 %   ┊   Installing: Done   ┊   Step: Installation completed   ┊   Step Time: 19s   ┊

cd test2-feb-2015/
clever install clever-orm

Attempting to install clever-orm...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-orm...
  ├── Installing NPM modules for clever-orm...
✔    Successfully installed clever-orm...
  ├── Installing bundledDependencies...
  ├── ⚠ Running grunt tasks for module clever-orm...
Running "prompt:cleverOrmConfigPrompt" (prompt) task
? Database username: root
? Database password: 
? Database name: nodeseed
? Database dialect: mysql
? Database host: 127.0.0.1
? Database port: 3306

Running "cleverOrmCreateConfig" task

Done, without errors.
Running database migrations...
✔  Successfully installed.

clever install clever-auth clever-users
Attempting to install clever-auth,clever-users...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-auth...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-auth...
✔    Successfully installed clever-auth...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing bundledDependencies...
  ├── ⚠ Running grunt tasks for module clever-auth...
Running "prompt:authConfigPrompt" (prompt) task
? What environment is this configuration for? LOCAL
? Secret key used to secure your passport sessions: lQrBDSZEclcyyalOs4pR
? What database driver module to use: ORM
? Session Storage Driver: redis
? Redis host: localhost
? Redis port: 6379
? Redis prefix: 
? Redis key: 

Running "createCleverAuthConfig" task

Done, without errors.
  ├── ⚠ Running grunt tasks for module clever-users...
Running "prompt:usersSeedDataPrompt" (prompt) task
? Default Username: default
? Default Users Password: ****************************************
? Default Users Email: default@cleverstack.io
? Default Users Firstname: Clever
? Default Users Lastname: User
? Default Users Phone Number: 
? Default User has admin rights: Yes
? Default User has confirmed their email: Yes
? Default User has an active account: Yes

Running "usersSeedData" task
You should run `grunt db` to rebase and seed this data in your database...

Done, without errors.
✔  Successfully installed.

clever install clever-accounts
Attempting to install clever-accounts...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-accounts...
  ├── Installing NPM modules for clever-accounts...
✔    Successfully installed clever-accounts...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /Users/richardgustin/Documents/Projects/CleverStack/Workspace/test2-feb-2015/modules/clever-accounts
  ├── Installing modules: clever-roles
✔      Found CleverStack Backend (node-seed) in /Users/richardgustin/Documents/Projects/CleverStack/Workspace/test2-feb-2015...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-roles...
  ├── Installing NPM modules for clever-roles...
✔    Successfully installed clever-roles...
  ├── Installing bundledDependencies...
✔  Successfully installed.
`
