### ISSUE TITLE
Install error: exec:ormPostInstall

### ISSUE THREAD

**Issue by DaBoogs** [CleverStack/clever-orm#41]
Running "cleverOrmCreateConfig" task

Running "exec:ormPostInstall" (exec) task
>> events.js:85
>>       throw er; // Unhandled 'error' event
>>             ^
>> Error: spawn npm ENOENT
>>     at exports._errnoException (util.js:746:11)
>>     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
>>     at child_process.js:1144:20
>>     at process._tickCallback (node.js:355:11)
>>     at Function.Module.runMain (module.js:503:11)
>>     at startup (node.js:129:16)
>>     at node.js:814:3
>> Exited with code: 1.
Warning: Task "exec:ormPostInstall" failed. Use --force to continue.

Aborted due to warnings.
Running database migrations...
?  Successfully installed.

Just trying to install out of the box based on instructions found at: https://github.com/CleverStack/cleverstack-cli

I'm looking for a FullStack that uses MySQL so I wanted to try cleverstack, but it seems you guys have a lot of initial setup issues :(

**Comment by pilsy** [comment]
@DaBoogs - i fixed this issue (it was window's specific) in https://github.com/CleverStack/clever-orm/releases/tag/2.0.8
